services:
  redis:
    image: redis:latest
    container_name: redis-gpo-local
    ports:
      - "5002:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
